let pokemonList = {};
pokemonList.name = "Bulbasaur";
pokemonList.height = 7;
pokemonList.types = ["grass", "poison"];
pokemonList.name = "Charmander";
pokemonList.height = 6;
pokemonList.types = ["fire"];
pokemonList.name = "Squirtle";
pokemonList.height = 5;
pokemonList.types = ["water"];
console.log(pokemonList);